// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWRmQM31ZqTOSS26rty7ixHeJUAP190b0',
    appId: '1:628162894772:web:2e68576eba74de2be7b0e1',
    messagingSenderId: '628162894772',
    projectId: 'm-link-sebn',
    authDomain: 'm-link-sebn.firebaseapp.com',
    storageBucket: 'm-link-sebn.firebasestorage.app',
    measurementId: 'G-S64L0WH18W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8wnvvX_mvPn6YPiUs7MIFxyr0qefjGg0',
    appId: '1:628162894772:android:8347923e0a054722e7b0e1',
    messagingSenderId: '628162894772',
    projectId: 'm-link-sebn',
    storageBucket: 'm-link-sebn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABgbk8_AmI465oH3cZI8OqEkGHFaXYaZc',
    appId: '1:628162894772:ios:00871cbe3a71cbd0e7b0e1',
    messagingSenderId: '628162894772',
    projectId: 'm-link-sebn',
    storageBucket: 'm-link-sebn.firebasestorage.app',
    iosBundleId: 'com.example.mLinkSebn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABgbk8_AmI465oH3cZI8OqEkGHFaXYaZc',
    appId: '1:628162894772:ios:00871cbe3a71cbd0e7b0e1',
    messagingSenderId: '628162894772',
    projectId: 'm-link-sebn',
    storageBucket: 'm-link-sebn.firebasestorage.app',
    iosBundleId: 'com.example.mLinkSebn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWRmQM31ZqTOSS26rty7ixHeJUAP190b0',
    appId: '1:628162894772:web:f15da9456940dff5e7b0e1',
    messagingSenderId: '628162894772',
    projectId: 'm-link-sebn',
    authDomain: 'm-link-sebn.firebaseapp.com',
    storageBucket: 'm-link-sebn.firebasestorage.app',
    measurementId: 'G-YWCMQLG8L1',
  );
}
